name: Dispatcher

on:
    push:
        branches:
            - main

jobs:
    trigger:
        runs-on: ubuntu-latest
        steps:
            - name: Trigger CI Workflow
              uses: peter-evans/workflow-dispatch@v3
              with:
                token: ${{ secrets.GITHUB_TOKEN }}
                repository: matusholka/fastapi-app
                event-type: trigger-ci