name: Test

on:
    repository_dispatch:
        types: [trigger-ci]

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
              - name: Checkout code
                uses: actions/checkout@v4
              - name: Set up Python
                uses: actions/setup-python@v5
                with:
                  python-version: '3.11'
              - name: Install dependencies
                run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt
              - name: Trigger Docker Build
                if: success()
                uses: peter-evans/repository-dispatch@v3
                with:
                  token: ${{ secrets.GITHUB_TOKEN }}
                  event-type: trigger-docker-build                  

