name: Docker Build and Push

on:
    workflow_run:
        workflows: ["01-ci.yaml"]
        types:
            - completed

jobs:
    build:
        if: ${{github.event.workflow_run.conclusion == 'success'}}
        runs-on: ubuntu-latest            
        steps:
            - uses: actions/checkout@v4

            - run: |
                docker build -t ${{ secrets.DOCKER_USERNAME }}/fastapi-app:latest .
                docker push ${{ secrets.DOCKER_USERNAME }}/fastapi-app:latest