name: Docker Build and Push

on:
    repository_dispatch:
        types: [trigger-docker-build]

jobs:
    build:
        runs-on: ubuntu-latest            
        steps:
            - run: |
                docker build -t ${{ secrets.DOCKER_USERNAME }}/fastapi-app:latest .
                docker push ${{ secrets.DOCKER_USERNAME }}/fastapi-app:latest                
    