name: Docker Build and Push

on:
    repository_dispatch:
        types: [trigger-docker-build]

jobs:
    build:
        runs-on: ubuntu-latest            
        steps:
          - name: Build and Push Docker Image
            run: |
              docker build -f ./Dockerfile -t ${{ secrets.DOCKER_USERNAME }}/fastapi-app:latest .
              docker push ${{ secrets.DOCKER_USERNAME }}/fastapi-app:latest
          - name: Trigger Terraform Apply
            if: ${{ success() }}
            uses: peter-evans/repository-dispatch@v3
            with:
              token: ${{ secrets.GITHUB_TOKEN }}
              event-type: trigger-terraform
    