name: Deploy to AKS using Helm

on:
    workflow_run:
        workflows: ["03-terraform.yaml"]
        types:
            - completed

jobs:
    deploy:
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        runs-on: ubuntu-latest
        
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Set up Helm
              uses: azure/setup-helm@v3

            - name : Azure Login
              uses: azure/login@v2
              with:
                  creds: ${{ secrets.AZURE_CREDENTIALS }}   
            - name: Deploy Helm Chart
              run: |                  
            
            - name: Get AKS credentials
              run: |
                az aks get-credentials --resource-group ${{ secrets.AKS_RESOURCE_GROUP }} --name ${{ secrets.AKS_CLUSTER_NAME }}

            - name: Deploy Helm Chart
              run: |
                helm upgrade --install fastapi-app ./helm/fastapi-app \
                 --namespace default \
                 --set image.repository=${{ secrets.DOCKER_USERNAME}} \
                 --set image.tag=latest \
                 --wait
